### ISSUE TITLE
Use the projects version of stylelint if it exists

### ISSUE THREAD

**Issue by chrishoage** [jo-sm/stylelint_d#4]
https://github.com/mantoni/eslint_d.js/blob/master/lib/linter.js

`eslint_d` tries to resolve a local copy of `eslint` before falling back to the shipped copy of `eslint`. 

It would be nice to not have to stay in lock step with the version of `stylelint` that ships with `stylelint_d`. 

With in reason of course, if there are methods or output that stylelint can't parse then the user should be expected to update. But the difference between v6 and v7 seems fairly minimal and mostly rule updates.

**Comment by jo-sm** [comment]
Initially I didn't attempt to use the local version because I realized I wasn't going to be able to support the CLI in the same way, since `stylelint` doesn't export their CLI classes directly. But after looking a little more closely at how `eslint_d` does its module resolution, I think it's actually relatively simple to allow this. I'll take a look soon.

**Comment by jo-sm** [comment]
So I gave this some thought, and came up with two possible solutions:

1. Go with this issue's proposed idea, and use the same method that `eslint_d` does to resolve modules, e.g. the `resolve` module with `{ basedir: ... }` as an option object;
2. Make the current version allowed in the `package.json` anything from `7.0.0` to `8`, so that the lint API doesn't change in a major version update and cause issues.

I'm leaning towards 1, because I would assume that the `stylelint` devs would deprecate the API rather than just change it, since it is officially supports and not internal, and the project moves relatively quickly and version 7 may be obsolete in the next month.

What do you think @chrishoage?

**Comment by chrishoage** [comment]
I'm leaning toward 1 as well. 

As long as the logging is decent `stylelint` deprecating an API shouldn't be a big deal. I think the fact that `stylelint_d` won't have to be updated _every_ time `stylelint` updates would be a win?

**Comment by jo-sm** [comment]
True, and looking at the old commits of their Node API docs, they've been using `stylelint.lint(opts)` for a while, so I don't assume it'll change anytime soon, and they would log deprecation if it did. I'll add in support for this ASAP.

**Comment by chrishoage** [comment]
Just wanted to say that this is working great. Background mode and our projects current stylelint version of 7.1.0 are humming along nicely. 

Thanks a ton!
